image: python:3.5

stages:
  - test
  - release

test:
  stage: test
  script:
    - python setup.py test


release:
  stage: release
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
    - dists
  only:
    - master
